### PR TITLE
JAMES-3715: Several fixes and improvements to make starting and managing netty servers easier

### PR DESCRIPTION
**Pull request by glennosss**
Several fixes and improvements to make starting and managing netty servers easier - specifically:
1. Created 'EventLoopGroupManager' interface - see interface javadoc for more information - allows much better control over starting/sharing EventLoopGroups - https://github.com/glennosss/james-project/blob/netty4-combo/protocols/netty/src/main/java/org/apache/james/protocols/netty/EventLoopGroupManager.java
2. Updated 'Encryption' to support old static methods, but added additional static methods which add Netty SslContext support - see 'Encryption' javadoc for more information - https://github.com/glennosss/james-project/blob/netty4-combo/protocols/api/src/main/java/org/apache/james/protocols/api/Encryption.java
3. See 'ProtocolServer' javadoc - now supports async bind/unbind, control over how long unbind takes, and added unbindNow() to help with instantly stopping server for unit tests - https://github.com/glennosss/james-project/blob/netty4-combo/protocols/api/src/main/java/org/apache/james/protocols/api/ProtocolServer.java
4. Updated 'NettyServer', 'AbstractAsyncServer' to support proper construction using Factory/Builder approach - making it much easier to method chain and build a server.
5. Updated 'AbstractConfigurableAsyncServer' to support Factory/Builder approach - also 'bossThreads' and 'keepalive' parameters are now configurable.

FYI Also includes a fix for TCP_NODELAY still wasn't being set properly (`configureBootstrap()` was being run after socket was bound).

### CODE REVIEW

**Comment by glennosss** [comment]
Created pull request as requested here: https://github.com/apache/james-project/pull/924#issuecomment-1074768865

**Comment by chibenwa** [comment]
Can you open it publicly against the ASF repo?

**Comment by glennosss** [comment]
Apologies I don't know how to do that - there's no https://github.com/apache/james-project/tree/netty4-combo branch - so I don't believe I can create a pull request against https://github.com/apache/james-project only against https://github.com/chibenwa/james-project

If you can provide instructions, I can try to follow them. Alternatively I was just expecting you to pull https://github.com/glennosss/james-project/tree/netty4-combo into https://github.com/chibenwa/james-project/tree/netty4-combo then we could view it from https://github.com/apache/james-project/pull/924

**Comment by glennosss** [comment]
Closing pull request - as sending this pull request instead: https://github.com/apache/james-project/pull/929

**Pull request closed without merging**
